version: "3.8"

services:
    app:
        build: ./infra/php
        volumes:
            - ../MRM:/work/MRM

    web:
        build: ./infra/nginx
        ports:
            - 10080:80
        volumes:
            - ../MRM:/work/MRM
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /work
    
    pra-db:
        build: ./infra/mysql
        ports:
            - 3306:3306
        volumes:
            - db-store:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_PORT=3306
            - PMA_HOST=pra-db
            - PMA_USER=mrmuser
            - PMA_PASSWORD=passwd00
        depends_on:
            - pra-db
        ports:
            - 28080:80
    
    mockapi:
        image: danielgtaylor/apisprout:latest
        container_name: 'mockapi'
        ports:
            - '9003:8000'
        volumes:
            - ../openapi.yaml:/openapi.yaml
        entrypoint: /usr/local/bin/apisprout /openapi.yaml --watch

volumes:
    db-store: